add_newline = false

[aws]
disabled = true

[git_branch]
style = "bright-white"

[git_status]
style = "yellow"

[nodejs]
disabled = true

[rust]
disabled = true

[python]
disabled = true

[package]
disabled = true