add_newline = false

[aws]
disabled = true

[git_branch]
style = "bright-white"

[git_status]
style = "yellow"

[nodejs]
disabled = true

[rust]
disabled = true

[python]
disabled = true

[package]
disabled = true

[gcloud]
format = 'on [$symbol(\($project\))]($style) '
[gcloud.region_aliases]
europe-west1 = "eu-w1"
europe-west2 = "eu-w2"